version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql

  mysql:
    image: mysql:latest
    container_name: mysql-db
    ports:
      - "${MYSQL_PORT}:3306"
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

  mongo:
    image: mongodb/mongodb-community-server:8.2-ubi8
    container_name: mongo-db
    ports:
      - "${MONGO_PORT}:27017"
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/configdb


volumes:
  postgres_data:
    external: true
    name: c1b7e8eae1b6ffe9cac6748da65cb7cce21687001e451d7bc97b4651f837a6d0
  mongo_data:
    external: true
    name: 866b4c7cb3ba0b6df0418d3951e9c8b67bfe344802f479f8a6eb9d66c28810eb
  mysql_data:
    external: true
    name: 23bef8d310972200ce0b1f2d2c66e932d8426dcc2746f14f08893c810830c586